openapi: 3.0.0
info:
  title: Image Processing API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /image:
    post:
      summary: Saves an image.
      description: Creates an image file on S3 and creates a record in the database.
      parameters:
        - name: image
          in: body
          required: true
          description: The image should be here.
      responses:
        "200": # status code
          description: A JSON object with the details of the created image
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: 5fd0bfb68c6e8e5df2562e3c
                  name:
                    type: string
                    example: tweety.jpg
    # "_id": "5fd0bfb68c6e8e5df2562e3c",
    # "id": "c2092c38-deb8-48d1-a9c6-d7bc7b2fa73a",
    # "created_at": "2020-12-09T12:14:46.915Z",
    # "name": "tweety.jpg",
    # "__v": 0
